version: 2 # use CircleCI 2.0

jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/php:7.1-node-browsers # ...with this image as the primary container; this is where all `steps` will run
    working_directory: ~/laravel # directory where steps will run
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - echo "Nothing here"

  deploy:
    docker:
      - image: circleci/python:3.7-stretch
    working_directory: ~/circleci-docs
    steps:
      # remember to add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: List S3 Buckets
          command: aws s3 ls

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy